### ISSUE TITLE
Generating the annotation file

### ISSUE THREAD

**Issue by franciscozorrilla** [biobakery/graphlan#4]
Hi,

I have a tree file that I generated using phylophlan based on ~4000 MAGs generated from normal, impaired, and T2D glucose control metagenomes. Now I want to annotate the tree with color to show which MAGs were reconstructed from which disease group.

Is there a simple/automated way of generating the annotation file like this [one](https://github.com/biobakery/graphlan/blob/master/examples/gut_microbiome/annot.txt) for my case or do I have to construct this manually?

Best wishes,
Francisco

**Comment by fasnicar** [comment]
Hi,

Thanks for using GraPhlAn. For the generation of the annotation we don't have a script that can help you, unfortunately, and this because there is no standard way people keep their metadata so it will be difficult to have one single script able to interpret any kind of metadata to generate the annotation.

In your case, the simplest way is to load in Python or R the set of MAGs assigned to each of the three categories and write the annotation file accordingly.

Many thanks,
Francesco

**Comment by franciscozorrilla** [comment]
Thanks for the quick response! Ah yes that was my backup plan, just wanted to check that there wasn't an easier way before parsing one myself. The annotation file format seemed intimating at first glance, but after looking at the examples and documentation in a bit more detail it makes sense to me now. Looking forward to making some nice trees!

Best wishes,
Francisco
